export const tamilNaduLocations = [
    "Tamil Nadu",
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Salem",
    "Tirunelveli",
    "Tiruppur",
    "Erode",
    "Vellore",
    "Thoothukudi",
    "Dindigul",
    "Thanjavur",
    "Ranipet",
    "Sivakasi",
    "Karur",
    "Udhagamandalam",
    "Ooty",
    "Hosur",
    "Nagercoil",
    "Kancheepuram",
    "Kumarapalayam",
    "Karaikkudi",
    "Neyveli",
    "Cuddalore",
    "Kumbakonam",
    "Tiruvannamalai",
    "Pollachi",
    "Rajapalayam",
    "Gudiyatham",
    "Pudukkottai",
    "Vaniyambadi",
    "Ambur",
    "Nagapattinam",
    "Mettupalayam",
    "Bhavani"
];

export const disasterKeywords = [
    "flood", "flooding", "cyclone", "storm", "heavy rain", "rainfall",
    "landslide", "earthquake", "tsunami", "water level", "dam", "river",
    "rescue", "evacuation", "trapped", "missing", "collapse", "road blocked",
    "emergency", "disaster"
];
